### ISSUE TITLE
Email address is not verified

### ISSUE THREAD

**Issue by colmex** [mardix/ses-mailer#2]
Getting this error when I try to send a mail. The email address is verified and they key is correct.

When I check

```
from ses_mailer import Mail
mail = Mail(aws_access_key_id="<KEY>", aws_secret_access_key="<KEY>", sender="<sender_email>", reply_to="<reply_to_email>")
mail.ses.host
```

I get 

```
'email.us-east-1.amazonaws.com'
```

but my area isn't us-east-1, I need us-west-2.
Is there any way to change the host?

**Comment by mardix** [comment]
It is now added and fixed. You can select a region. Version: 0.13.0
